### PR TITLE
Fix setup.py importing the whole module

### PR DESCRIPTION
**Pull request by AbdealiLoKo**

### CODE REVIEW

**Comment by AbdealiLoKo** [comment]
@jayvdb would you like to +2 this so I can merge it ?

**Comment by jayvdb** [comment]
Im stuck in low internet atm, so can verify it is all good. Probably necessary to add a MANIFEST.in , so the readme and other files are included in the pypi tarball.

**Comment by AbdealiLoKo** [comment]
@jayvdb Did you mean "**can't** verify it's all good" ?

**Comment by jayvdb** [comment]
Yes. Cant.
Adding Appveyor testing can help.

**Pull request merged**
